### PR TITLE
Added CommandTrace and MissionTrace data structures (fixes #150)

### LINKED ISSUE #150: Design and implement MissionTrace
```
@attr.s
class MissionTrace(object):
  commands = attr.ib(type=Tuple[CommandTrace])

@attr.s
class CommandTrace(object):
  states = attr.ib(type=Tuple[State])
  messages = attr.ib(type=Tuple[Message])
  coverage = attr.ib(type=Optional[Coverage])
```

### PR DESCRIPTION
**Pull request by ChrisTimperley**
* added `CommandTrace` for recording the observed states, sent and received messages, and the set of covered lines for a given command.
* added `MissionTrace` for recording traces for a sequence of commands.
* replaced `Recorder` with `TraceRecorder`: no longer writes to a given file, but instead maintains buffers which are flushed at the end of a command execution.

### CODE REVIEW

**Comment by ChrisTimperley** [comment]
```
(houston-Uzd7zXQ0) chris@chris-Blade:~/tools/houston$ python experiments/build_traces.py missions.json 
preparing containers
prepared containers
generating trace for mission 0: 2f8a05d4
[Errno 111] Connection refused sleeping
>>> APM:Copter V3.5-dev (b910f230)
>>> Frame: QUAD
>>> EKF2 IMU1 Origin set to GPS
>>> EKF2 IMU0 Origin set to GPS
>>> EKF2 IMU0 is using GPS
>>> EKF2 IMU1 is using GPS
waiting for the rover to be armed...
>>> Flight plan received
>>> Arming motors
waiting for the rover to be armed...
waiting for the rover to be armed...
waiting for the rover to be armed...
waiting for the rover to be armed...
waiting for the rover to be armed...
last_wp: [0, 1] len: 7
>>> Link timeout, no heartbeat in last 5 seconds
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/chris/.local/share/virtualenvs/houston-Uzd7zXQ0/lib/python3.6/site-packages/dronekit/mavlink.py", line 211, in mavlink_thread_in
    fn(self)
  File "/home/chris/.local/share/virtualenvs/houston-Uzd7zXQ0/lib/python3.6/site-packages/dronekit/__init__.py", line 1346, in listener
    self._heartbeat_error)
dronekit.APIException: No heartbeat in 30 seconds, aborting.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/chris/.local/share/virtualenvs/houston-Uzd7zXQ0/lib/python3.6/site-packages/dronekit/mavlink.py", line 240, in mavlink_thread_in
    errprinter('>>> ' + str(e.message))
AttributeError: 'APIException' object has no attribute 'message'
```

**Comment by afsafzal** [comment]
When `build_traces` is building many traces, it stops working because it seems to not properly close some files:
```
failed to build trace 475: 512eae84
Traceback (most recent call last):
  File "experiments/build_traces.py", line 69, in trace
    trace = sandbox.run_and_trace(mission.commands)
  File "/home/afsoon/Houston-forked/houston/ardu/sandbox.py", line 345, in run_and_trace
    coverage = self.__get_coverage(directory=directory)
  File "/home/afsoon/Houston-forked/houston/ardu/sandbox.py", line 362, in __get_coverage
    coverage = self._bugzoo.coverage.extract(self.container)
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/bugzoo/mgr/coverage.py", line 325, in extract
    mgr_ctr.copy_from(container, fn_temp_ctr, fn_temp_host)
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/bugzoo/mgr/container.py", line 478, in copy_from
    subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1454, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
generating trace for mission 478: 5fa8c670
>>> Skipping invalid cmd #176^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
last_wp: [2, 5] len: 10
failed to build trace 477: 2d3183ea
Traceback (most recent call last):
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
  File "/usr/lib/python3.5/http/client.py", line 877, in send
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/docker/transport/unixconn.py", line 44, in connect
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/requests/adapters.py", line 445, in send
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
  File "/usr/lib/python3.5/http/client.py", line 877, in send
  File "/home/afsoon/python3.5-venv/lib/python3.5/site-packages/docker/transport/unixconn.py", line 44, in connect
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(24, 'Too many open files'))
```

and it goes on and on. I couldn't find any files that are opened but not closed. My suspicion is the coverage extract. Can not removing temp files result in this?

**Comment by ChrisTimperley** [comment]
> When `build_traces` is building many traces, it stops working because it seems to not properly close some files:
> 
> ....
>
> and it goes on and on. I couldn't find any files that are opened but not closed. My suspicion is the coverage extract. Can not removing temp files result in this?

Did increasing the open file limit avoid the issue?

**Comment by afsafzal** [comment]
@ChrisTimperley I didn't try that. I stopped collecting coverage data which avoided the problem. It is still running and I haven't seen the exception yet.

**Comment by ChrisTimperley** [comment]
Can we go ahead and merge this, @afsafzal?

**Pull request merged**
